"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

"preserve_hierarchy": true
"base_path": "."

files:
  - source: /locale/en-US/*.ftl
    translation: /locale/%locale%/%original_file_name%
